import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting seed...');

  // Create parent account with default PIN "1234"
  const pinHash = await bcrypt.hash('1234', 10);
  const parentAccount = await prisma.parentAccount.upsert({
    where: { id: 'default-parent' },
    update: {},
    create: {
      id: 'default-parent',
      pinHash,
      settingsJson: JSON.stringify({
        questionTypes: {
          enToHe: true,
          heToEn: true,
          audioToEn: false, // Not default - user can enable if they want
        },
      }),
    },
  });

  console.log('✅ Parent account created');

  // Seed letters (A-Z)
  const letters = [
    { letter: 'A', name: 'A', hebrewName: 'איי', sound: '/eɪ/', order: 1 },
    { letter: 'B', name: 'Bee', hebrewName: 'בי', sound: '/biː/', order: 2 },
    { letter: 'C', name: 'Cee', hebrewName: 'סי', sound: '/siː/', order: 3 },
    { letter: 'D', name: 'Dee', hebrewName: 'די', sound: '/diː/', order: 4 },
    { letter: 'E', name: 'E', hebrewName: 'אי', sound: '/iː/', order: 5 },
    { letter: 'F', name: 'Ef', hebrewName: 'אף', sound: '/ef/', order: 6 },
    { letter: 'G', name: 'Gee', hebrewName: 'גי', sound: '/dʒiː/', order: 7 },
    { letter: 'H', name: 'Aitch', hebrewName: 'אייץ', sound: '/eɪtʃ/', order: 8 },
    { letter: 'I', name: 'I', hebrewName: 'איי', sound: '/aɪ/', order: 9 },
    { letter: 'J', name: 'Jay', hebrewName: 'גיי', sound: '/dʒeɪ/', order: 10 },
    { letter: 'K', name: 'Kay', hebrewName: 'קיי', sound: '/keɪ/', order: 11 },
    { letter: 'L', name: 'El', hebrewName: 'אל', sound: '/el/', order: 12 },
    { letter: 'M', name: 'Em', hebrewName: 'אם', sound: '/em/', order: 13 },
    { letter: 'N', name: 'En', hebrewName: 'אן', sound: '/en/', order: 14 },
    { letter: 'O', name: 'O', hebrewName: 'או', sound: '/oʊ/', order: 15 },
    { letter: 'P', name: 'Pee', hebrewName: 'פי', sound: '/piː/', order: 16 },
    { letter: 'Q', name: 'Cue', hebrewName: 'קיו', sound: '/kjuː/', order: 17 },
    { letter: 'R', name: 'Ar', hebrewName: 'אר', sound: '/ɑːr/', order: 18 },
    { letter: 'S', name: 'Ess', hebrewName: 'אס', sound: '/es/', order: 19 },
    { letter: 'T', name: 'Tee', hebrewName: 'טי', sound: '/tiː/', order: 20 },
    { letter: 'U', name: 'U', hebrewName: 'יו', sound: '/juː/', order: 21 },
    { letter: 'V', name: 'Vee', hebrewName: 'וי', sound: '/viː/', order: 22 },
    { letter: 'W', name: 'Double-U', hebrewName: 'דאבל יו', sound: '/ˈdʌbəl.juː/', order: 23 },
    { letter: 'X', name: 'Ex', hebrewName: 'אקס', sound: '/eks/', order: 24 },
    { letter: 'Y', name: 'Wy', hebrewName: 'וואי', sound: '/waɪ/', order: 25 },
    { letter: 'Z', name: 'Zed', hebrewName: 'זד', sound: '/zed/', order: 26 },
  ];

  for (const letterData of letters) {
    await prisma.letter.upsert({
      where: { letter: letterData.letter },
      update: {},
      create: {
        ...letterData,
        active: true,
      },
    });
  }

  console.log('✅ Created 26 letters');

  // Create default child
  const child = await prisma.childProfile.upsert({
    where: { id: 'default-child' },
    update: {},
    create: {
      id: 'default-child',
      parentAccountId: parentAccount.id,
      name: 'ילד/ה',
      avatar: '👶',
      age: 10,
      grade: 'ד',
    },
  });

  // Update parent's lastActiveChildId
  await prisma.parentAccount.update({
    where: { id: parentAccount.id },
    data: { lastActiveChildId: child.id },
  });

  console.log('✅ Default child created');

  // Seed words - at least 60 beginner words
  const words = [
    // Home category Level 2 (difficulty 1) - 20 words
    { englishWord: 'house', hebrewTranslation: 'בית', category: 'Home', difficulty: 1, exampleEn: 'This is my house', exampleHe: 'זה הבית שלי' },
    { englishWord: 'room', hebrewTranslation: 'חדר', category: 'Home', difficulty: 1, exampleEn: 'My room is big', exampleHe: 'החדר שלי גדול' },
    { englishWord: 'bed', hebrewTranslation: 'מיטה', category: 'Home', difficulty: 1, exampleEn: 'I sleep in my bed', exampleHe: 'אני ישן במיטה שלי' },
    { englishWord: 'chair', hebrewTranslation: 'כיסא', category: 'Home', difficulty: 1, exampleEn: 'Sit on the chair', exampleHe: 'שב על הכיסא' },
    { englishWord: 'table', hebrewTranslation: 'שולחן', category: 'Home', difficulty: 1, exampleEn: 'The table is round', exampleHe: 'השולחן עגול' },
    { englishWord: 'door', hebrewTranslation: 'דלת', category: 'Home', difficulty: 1, exampleEn: 'Close the door', exampleHe: 'סגור את הדלת' },
    { englishWord: 'window', hebrewTranslation: 'חלון', category: 'Home', difficulty: 1, exampleEn: 'Open the window', exampleHe: 'פתח את החלון' },
    { englishWord: 'kitchen', hebrewTranslation: 'מטבח', category: 'Home', difficulty: 1, exampleEn: 'Mom is in the kitchen', exampleHe: 'אמא במטבח' },
    { englishWord: 'bathroom', hebrewTranslation: 'שירותים', category: 'Home', difficulty: 1, exampleEn: 'Where is the bathroom?', exampleHe: 'איפה השירותים?' },
    { englishWord: 'garden', hebrewTranslation: 'גן', category: 'Home', difficulty: 1, exampleEn: 'We play in the garden', exampleHe: 'אנחנו משחקים בגן' },
    { englishWord: 'sofa', hebrewTranslation: 'ספה', category: 'Home', difficulty: 1, exampleEn: 'The sofa is comfortable', exampleHe: 'הספה נוחה' },
    { englishWord: 'lamp', hebrewTranslation: 'מנורה', category: 'Home', difficulty: 1, exampleEn: 'Turn on the lamp', exampleHe: 'הדלק את המנורה' },
    { englishWord: 'computer', hebrewTranslation: 'מחשב', category: 'Home', difficulty: 1, exampleEn: 'I use the computer', exampleHe: 'אני משתמש במחשב' },
    { englishWord: 'phone', hebrewTranslation: 'טלפון', category: 'Home', difficulty: 1, exampleEn: 'My phone is new', exampleHe: 'הטלפון שלי חדש' },
    { englishWord: 'television', hebrewTranslation: 'טלוויזיה', category: 'Home', difficulty: 1, exampleEn: 'Watch television', exampleHe: 'צפה בטלוויזיה' },
    { englishWord: 'refrigerator', hebrewTranslation: 'מקרר', category: 'Home', difficulty: 1, exampleEn: 'The food is in the refrigerator', exampleHe: 'האוכל במקרר' },
    { englishWord: 'cup', hebrewTranslation: 'כוס', category: 'Home', difficulty: 1, exampleEn: 'Drink from the cup', exampleHe: 'שתה מהכוס' },
    { englishWord: 'plate', hebrewTranslation: 'צלחת', category: 'Home', difficulty: 1, exampleEn: 'Put food on the plate', exampleHe: 'שים אוכל על הצלחת' },
    { englishWord: 'spoon', hebrewTranslation: 'כף', category: 'Home', difficulty: 1, exampleEn: 'Use a spoon', exampleHe: 'השתמש בכף' },
    { englishWord: 'fork', hebrewTranslation: 'מזלג', category: 'Home', difficulty: 1, exampleEn: 'Eat with a fork', exampleHe: 'אכול עם מזלג' },

    // School category (20+ words)
    { englishWord: 'school', hebrewTranslation: 'בית ספר', category: 'School', difficulty: 1, exampleEn: 'I go to school', exampleHe: 'אני הולך לבית ספר' },
    { englishWord: 'teacher', hebrewTranslation: 'מורה', category: 'School', difficulty: 1, exampleEn: 'The teacher is nice', exampleHe: 'המורה נחמדה' },
    { englishWord: 'student', hebrewTranslation: 'תלמיד', category: 'School', difficulty: 1, exampleEn: 'I am a student', exampleHe: 'אני תלמיד' },
    { englishWord: 'classroom', hebrewTranslation: 'כיתה', category: 'School', difficulty: 1, exampleEn: 'Our classroom is big', exampleHe: 'הכיתה שלנו גדולה' },
    { englishWord: 'desk', hebrewTranslation: 'שולחן כתיבה', category: 'School', difficulty: 1, exampleEn: 'Sit at your desk', exampleHe: 'שב בשולחן הכתיבה שלך' },
    { englishWord: 'pencil', hebrewTranslation: 'עיפרון', category: 'School', difficulty: 1, exampleEn: 'Write with a pencil', exampleHe: 'כתוב בעיפרון' },
    { englishWord: 'pen', hebrewTranslation: 'עט', category: 'School', difficulty: 1, exampleEn: 'I need a pen', exampleHe: 'אני צריך עט' },
    { englishWord: 'notebook', hebrewTranslation: 'מחברת', category: 'School', difficulty: 1, exampleEn: 'Write in your notebook', exampleHe: 'כתוב במחברת שלך' },
    { englishWord: 'backpack', hebrewTranslation: 'תיק', category: 'School', difficulty: 1, exampleEn: 'Put books in your backpack', exampleHe: 'שים ספרים בתיק שלך' },
    { englishWord: 'homework', hebrewTranslation: 'שיעורי בית', category: 'School', difficulty: 1, exampleEn: 'Do your homework', exampleHe: 'עשה את שיעורי הבית שלך' },
    { englishWord: 'test', hebrewTranslation: 'מבחן', category: 'School', difficulty: 1, exampleEn: 'I have a test tomorrow', exampleHe: 'יש לי מבחן מחר' },
    { englishWord: 'lesson', hebrewTranslation: 'שיעור', category: 'School', difficulty: 1, exampleEn: 'The lesson is interesting', exampleHe: 'השיעור מעניין' },
    { englishWord: 'blackboard', hebrewTranslation: 'לוח', category: 'School', difficulty: 1, exampleEn: 'Look at the blackboard', exampleHe: 'הסתכל על הלוח' },
    { englishWord: 'eraser', hebrewTranslation: 'מחק', category: 'School', difficulty: 1, exampleEn: 'Use the eraser', exampleHe: 'השתמש במחק' },
    { englishWord: 'ruler', hebrewTranslation: 'סרגל', category: 'School', difficulty: 1, exampleEn: 'Measure with a ruler', exampleHe: 'מדוד עם סרגל' },
    { englishWord: 'calculator', hebrewTranslation: 'מחשבון', category: 'School', difficulty: 1, exampleEn: 'Use a calculator', exampleHe: 'השתמש במחשבון' },
    { englishWord: 'library', hebrewTranslation: 'ספרייה', category: 'School', difficulty: 1, exampleEn: 'Borrow books from the library', exampleHe: 'השאל ספרים מהספרייה' },
    { englishWord: 'playground', hebrewTranslation: 'מגרש משחקים', category: 'School', difficulty: 1, exampleEn: 'Play in the playground', exampleHe: 'שחק במגרש המשחקים' },
    { englishWord: 'recess', hebrewTranslation: 'הפסקה', category: 'School', difficulty: 1, exampleEn: 'We play during recess', exampleHe: 'אנחנו משחקים בהפסקה' },
    { englishWord: 'grade', hebrewTranslation: 'ציון', category: 'School', difficulty: 1, exampleEn: 'I got a good grade', exampleHe: 'קיבלתי ציון טוב' },
    
    // School category Level 3 (difficulty 2) - 20 words - simpler words
    { englishWord: 'book', hebrewTranslation: 'ספר', category: 'School', difficulty: 2, exampleEn: 'Read a book', exampleHe: 'קרא ספר' },
    { englishWord: 'bag', hebrewTranslation: 'תיק', category: 'School', difficulty: 2, exampleEn: 'School bag', exampleHe: 'תיק בית ספר' },
    { englishWord: 'chair', hebrewTranslation: 'כיסא', category: 'School', difficulty: 2, exampleEn: 'Sit on a chair', exampleHe: 'שב על כיסא' },
    { englishWord: 'desk', hebrewTranslation: 'שולחן', category: 'School', difficulty: 2, exampleEn: 'Write on the desk', exampleHe: 'כתוב על השולחן' },
    { englishWord: 'marker', hebrewTranslation: 'טוש', category: 'School', difficulty: 2, exampleEn: 'Color with a marker', exampleHe: 'צבע עם טוש' },
    { englishWord: 'crayon', hebrewTranslation: 'צבעוני', category: 'School', difficulty: 2, exampleEn: 'Draw with crayons', exampleHe: 'צייר עם צבעונים' },
    { englishWord: 'glue', hebrewTranslation: 'דבק', category: 'School', difficulty: 2, exampleEn: 'Use glue', exampleHe: 'השתמש בדבק' },
    { englishWord: 'scissors', hebrewTranslation: 'מספריים', category: 'School', difficulty: 2, exampleEn: 'Cut with scissors', exampleHe: 'גזור עם מספריים' },
    { englishWord: 'paper', hebrewTranslation: 'נייר', category: 'School', difficulty: 2, exampleEn: 'Write on paper', exampleHe: 'כתוב על נייר' },
    { englishWord: 'folder', hebrewTranslation: 'תיקייה', category: 'School', difficulty: 2, exampleEn: 'Put papers in folder', exampleHe: 'שים ניירות בתיקייה' },
    { englishWord: 'binder', hebrewTranslation: 'קלסר', category: 'School', difficulty: 2, exampleEn: 'School binder', exampleHe: 'קלסר בית ספר' },
    { englishWord: 'stapler', hebrewTranslation: 'מהדק', category: 'School', difficulty: 2, exampleEn: 'Use a stapler', exampleHe: 'השתמש במהדק' },
    { englishWord: 'board', hebrewTranslation: 'לוח', category: 'School', difficulty: 2, exampleEn: 'Look at the board', exampleHe: 'הסתכל על הלוח' },
    { englishWord: 'chalk', hebrewTranslation: 'גיר', category: 'School', difficulty: 2, exampleEn: 'Write with chalk', exampleHe: 'כתוב עם גיר' },
    { englishWord: 'sharpener', hebrewTranslation: 'מחדד', category: 'School', difficulty: 2, exampleEn: 'Sharpen a pencil', exampleHe: 'חדד עיפרון' },
    { englishWord: 'compass', hebrewTranslation: 'מחוגה', category: 'School', difficulty: 2, exampleEn: 'Draw a circle', exampleHe: 'צייר עיגול' },
    { englishWord: 'protractor', hebrewTranslation: 'מעברת', category: 'School', difficulty: 2, exampleEn: 'Measure angles', exampleHe: 'מדוד זוויות' },
    { englishWord: 'highlighter', hebrewTranslation: 'מרקר', category: 'School', difficulty: 2, exampleEn: 'Highlight text', exampleHe: 'סמן טקסט' },
    { englishWord: 'clip', hebrewTranslation: 'קליפ', category: 'School', difficulty: 2, exampleEn: 'Paper clip', exampleHe: 'קליפ נייר' },
    { englishWord: 'tape', hebrewTranslation: 'סקוטש', category: 'School', difficulty: 2, exampleEn: 'Sticky tape', exampleHe: 'סקוטש דביק' },

    // Animals category (20 words)
    { englishWord: 'cat', hebrewTranslation: 'חתול', category: 'Animals', difficulty: 1, exampleEn: 'The cat is sleeping', exampleHe: 'החתול ישן' },
    { englishWord: 'dog', hebrewTranslation: 'כלב', category: 'Animals', difficulty: 1, exampleEn: 'The dog is friendly', exampleHe: 'הכלב ידידותי' },
    { englishWord: 'bird', hebrewTranslation: 'ציפור', category: 'Animals', difficulty: 1, exampleEn: 'The bird is flying', exampleHe: 'הציפור עפה' },
    { englishWord: 'fish', hebrewTranslation: 'דג', category: 'Animals', difficulty: 1, exampleEn: 'Fish live in water', exampleHe: 'דגים חיים במים' },
    { englishWord: 'rabbit', hebrewTranslation: 'ארנב', category: 'Animals', difficulty: 1, exampleEn: 'The rabbit is cute', exampleHe: 'הארנב חמוד' },
    { englishWord: 'horse', hebrewTranslation: 'סוס', category: 'Animals', difficulty: 1, exampleEn: 'I ride a horse', exampleHe: 'אני רוכב על סוס' },
    { englishWord: 'cow', hebrewTranslation: 'פרה', category: 'Animals', difficulty: 1, exampleEn: 'The cow gives milk', exampleHe: 'הפרה נותנת חלב' },
    { englishWord: 'sheep', hebrewTranslation: 'כבשה', category: 'Animals', difficulty: 1, exampleEn: 'White sheep', exampleHe: 'כבשה לבנה' },
    { englishWord: 'pig', hebrewTranslation: 'חזיר', category: 'Animals', difficulty: 1, exampleEn: 'The pig is pink', exampleHe: 'החזיר ורוד' },
    { englishWord: 'duck', hebrewTranslation: 'ברווז', category: 'Animals', difficulty: 1, exampleEn: 'The duck swims', exampleHe: 'הברווז שוחה' },
    { englishWord: 'chicken', hebrewTranslation: 'תרנגולת', category: 'Animals', difficulty: 1, exampleEn: 'The chicken lays eggs', exampleHe: 'התרנגולת מטילה ביצים' },
    { englishWord: 'mouse', hebrewTranslation: 'עכבר', category: 'Animals', difficulty: 1, exampleEn: 'The mouse is small', exampleHe: 'העכבר קטן' },
    { englishWord: 'bear', hebrewTranslation: 'דוב', category: 'Animals', difficulty: 1, exampleEn: 'The bear is big', exampleHe: 'הדוב גדול' },
    { englishWord: 'tiger', hebrewTranslation: 'נמר', category: 'Animals', difficulty: 1, exampleEn: 'The tiger has stripes', exampleHe: 'לנמר יש פסים' },
    { englishWord: 'monkey', hebrewTranslation: 'קוף', category: 'Animals', difficulty: 1, exampleEn: 'The monkey climbs', exampleHe: 'הקוף מטפס' },
    { englishWord: 'giraffe', hebrewTranslation: 'ג\'ירף', category: 'Animals', difficulty: 1, exampleEn: 'The giraffe is tall', exampleHe: 'הג\'ירף גבוה' },
    { englishWord: 'zebra', hebrewTranslation: 'זברה', category: 'Animals', difficulty: 1, exampleEn: 'The zebra has stripes', exampleHe: 'לזברה יש פסים' },
    { englishWord: 'wolf', hebrewTranslation: 'זאב', category: 'Animals', difficulty: 1, exampleEn: 'The wolf howls', exampleHe: 'הזאב מיילל' },
    { englishWord: 'deer', hebrewTranslation: 'צבי', category: 'Animals', difficulty: 1, exampleEn: 'The deer runs fast', exampleHe: 'הצבי רץ מהר' },
    { englishWord: 'fox', hebrewTranslation: 'שועל', category: 'Animals', difficulty: 1, exampleEn: 'The fox is clever', exampleHe: 'השועל חכם' },
    { englishWord: 'rooster', hebrewTranslation: 'תרנגול', category: 'Animals', difficulty: 2, exampleEn: 'The rooster crows', exampleHe: 'התרנגול קורא' },
    { englishWord: 'turkey', hebrewTranslation: 'תרנגול הודו', category: 'Animals', difficulty: 2, exampleEn: 'The turkey gobbles', exampleHe: 'תרנגול ההודו מקרקר' },
    { englishWord: 'parrot', hebrewTranslation: 'תוכי', category: 'Animals', difficulty: 2, exampleEn: 'The parrot talks', exampleHe: 'התוכי מדבר' },
    { englishWord: 'canary', hebrewTranslation: 'קנרית', category: 'Animals', difficulty: 2, exampleEn: 'The canary sings', exampleHe: 'הקנרית שרה' },
    { englishWord: 'hamster', hebrewTranslation: 'אוגר', category: 'Animals', difficulty: 2, exampleEn: 'The hamster runs', exampleHe: 'האוגר רץ' },
    { englishWord: 'guinea', hebrewTranslation: 'שרקן', category: 'Animals', difficulty: 2, exampleEn: 'The guinea pig squeaks', exampleHe: 'השרקן מצפצף' },
    { englishWord: 'turtle', hebrewTranslation: 'צב', category: 'Animals', difficulty: 2, exampleEn: 'The turtle walks slowly', exampleHe: 'הצב הולך לאט' },
    { englishWord: 'goldfish', hebrewTranslation: 'דג זהב', category: 'Animals', difficulty: 2, exampleEn: 'Goldfish in a bowl', exampleHe: 'דג זהב בקערה' },
    { englishWord: 'bunny', hebrewTranslation: 'ארנבון', category: 'Animals', difficulty: 2, exampleEn: 'Cute bunny', exampleHe: 'ארנבון חמוד' },
    { englishWord: 'puppy', hebrewTranslation: 'גור כלב', category: 'Animals', difficulty: 2, exampleEn: 'Playful puppy', exampleHe: 'גור כלב שובב' },
    { englishWord: 'kitten', hebrewTranslation: 'גור חתול', category: 'Animals', difficulty: 2, exampleEn: 'Cute kitten', exampleHe: 'גור חתול חמוד' },
    { englishWord: 'chick', hebrewTranslation: 'אפרוח', category: 'Animals', difficulty: 2, exampleEn: 'Yellow chick', exampleHe: 'אפרוח צהוב' },
    { englishWord: 'duckling', hebrewTranslation: 'ברווזון', category: 'Animals', difficulty: 2, exampleEn: 'Little duckling', exampleHe: 'ברווזון קטן' },
    { englishWord: 'lamb', hebrewTranslation: 'טלה', category: 'Animals', difficulty: 2, exampleEn: 'Little lamb', exampleHe: 'טלה קטן' },
    { englishWord: 'calf', hebrewTranslation: 'עגל', category: 'Animals', difficulty: 2, exampleEn: 'Baby calf', exampleHe: 'עגל קטן' },
    { englishWord: 'pony', hebrewTranslation: 'פוני', category: 'Animals', difficulty: 2, exampleEn: 'Ride a pony', exampleHe: 'רכב על פוני' },
    { englishWord: 'piglet', hebrewTranslation: 'חזרזיר', category: 'Animals', difficulty: 2, exampleEn: 'Small piglet', exampleHe: 'חזרזיר קטן' },
    { englishWord: 'cub', hebrewTranslation: 'גור', category: 'Animals', difficulty: 2, exampleEn: 'Bear cub', exampleHe: 'גור דוב' },
    { englishWord: 'foal', hebrewTranslation: 'סייח', category: 'Animals', difficulty: 2, exampleEn: 'Baby foal', exampleHe: 'סייח קטן' },
    { englishWord: 'kid', hebrewTranslation: 'גדי', category: 'Animals', difficulty: 2, exampleEn: 'Baby goat', exampleHe: 'גדי קטן' },

    // Colors category (20 words)
    { englishWord: 'red', hebrewTranslation: 'אדום', category: 'Colors', difficulty: 1, exampleEn: 'The apple is red', exampleHe: 'התפוח אדום' },
    { englishWord: 'blue', hebrewTranslation: 'כחול', category: 'Colors', difficulty: 1, exampleEn: 'The sky is blue', exampleHe: 'השמיים כחולים' },
    { englishWord: 'green', hebrewTranslation: 'ירוק', category: 'Colors', difficulty: 1, exampleEn: 'The grass is green', exampleHe: 'הדשא ירוק' },
    { englishWord: 'yellow', hebrewTranslation: 'צהוב', category: 'Colors', difficulty: 1, exampleEn: 'The sun is yellow', exampleHe: 'השמש צהובה' },
    { englishWord: 'orange', hebrewTranslation: 'כתום', category: 'Colors', difficulty: 1, exampleEn: 'The orange is orange', exampleHe: 'התפוז כתום' },
    { englishWord: 'purple', hebrewTranslation: 'סגול', category: 'Colors', difficulty: 1, exampleEn: 'I like purple', exampleHe: 'אני אוהב סגול' },
    { englishWord: 'black', hebrewTranslation: 'שחור', category: 'Colors', difficulty: 1, exampleEn: 'The night is black', exampleHe: 'הלילה שחור' },
    { englishWord: 'white', hebrewTranslation: 'לבן', category: 'Colors', difficulty: 1, exampleEn: 'Snow is white', exampleHe: 'השלג לבן' },
    { englishWord: 'pink', hebrewTranslation: 'ורוד', category: 'Colors', difficulty: 1, exampleEn: 'Pink flowers', exampleHe: 'פרחים ורודים' },
    { englishWord: 'brown', hebrewTranslation: 'חום', category: 'Colors', difficulty: 1, exampleEn: 'Brown bear', exampleHe: 'דוב חום' },
    { englishWord: 'gray', hebrewTranslation: 'אפור', category: 'Colors', difficulty: 1, exampleEn: 'Gray clouds', exampleHe: 'עננים אפורים' },
    { englishWord: 'gold', hebrewTranslation: 'זהב', category: 'Colors', difficulty: 1, exampleEn: 'Gold medal', exampleHe: 'מדליית זהב' },
    { englishWord: 'silver', hebrewTranslation: 'כסף', category: 'Colors', difficulty: 1, exampleEn: 'Silver coin', exampleHe: 'מטבע כסף' },
    { englishWord: 'turquoise', hebrewTranslation: 'טורקיז', category: 'Colors', difficulty: 1, exampleEn: 'Turquoise sea', exampleHe: 'ים טורקיז' },
    { englishWord: 'violet', hebrewTranslation: 'סגול כהה', category: 'Colors', difficulty: 1, exampleEn: 'Violet flowers', exampleHe: 'פרחים סגולים' },
    { englishWord: 'beige', hebrewTranslation: 'בז', category: 'Colors', difficulty: 1, exampleEn: 'Beige wall', exampleHe: 'קיר בז' },
    { englishWord: 'navy', hebrewTranslation: 'כחול כהה', category: 'Colors', difficulty: 1, exampleEn: 'Navy blue', exampleHe: 'כחול כהה' },
    { englishWord: 'lime', hebrewTranslation: 'ליים', category: 'Colors', difficulty: 1, exampleEn: 'Lime green', exampleHe: 'ירוק ליים' },
    { englishWord: 'maroon', hebrewTranslation: 'חום אדמדם', category: 'Colors', difficulty: 1, exampleEn: 'Maroon shirt', exampleHe: 'חולצה חומה אדמדמה' },
    { englishWord: 'cyan', hebrewTranslation: 'ציאן', category: 'Colors', difficulty: 1, exampleEn: 'Cyan sky', exampleHe: 'שמיים ציאן' },
    { englishWord: 'light', hebrewTranslation: 'בהיר', category: 'Colors', difficulty: 2, exampleEn: 'Light blue', exampleHe: 'כחול בהיר' },
    { englishWord: 'dark', hebrewTranslation: 'כהה', category: 'Colors', difficulty: 2, exampleEn: 'Dark green', exampleHe: 'ירוק כהה' },
    { englishWord: 'bright', hebrewTranslation: 'זוהר', category: 'Colors', difficulty: 2, exampleEn: 'Bright yellow', exampleHe: 'צהוב זוהר' },
    { englishWord: 'pale', hebrewTranslation: 'חיוור', category: 'Colors', difficulty: 2, exampleEn: 'Pale pink', exampleHe: 'ורוד חיוור' },
    { englishWord: 'deep', hebrewTranslation: 'עמוק', category: 'Colors', difficulty: 2, exampleEn: 'Deep blue', exampleHe: 'כחול עמוק' },
    { englishWord: 'soft', hebrewTranslation: 'רך', category: 'Colors', difficulty: 2, exampleEn: 'Soft color', exampleHe: 'צבע רך' },
    { englishWord: 'vivid', hebrewTranslation: 'עז', category: 'Colors', difficulty: 2, exampleEn: 'Vivid red', exampleHe: 'אדום עז' },
    { englishWord: 'muted', hebrewTranslation: 'מעומעם', category: 'Colors', difficulty: 2, exampleEn: 'Muted tone', exampleHe: 'גוון מעומעם' },
    { englishWord: 'neon', hebrewTranslation: 'ניאון', category: 'Colors', difficulty: 2, exampleEn: 'Neon green', exampleHe: 'ירוק ניאון' },
    { englishWord: 'pastel', hebrewTranslation: 'פסטל', category: 'Colors', difficulty: 2, exampleEn: 'Pastel blue', exampleHe: 'כחול פסטל' },
    { englishWord: 'shiny', hebrewTranslation: 'מבריק', category: 'Colors', difficulty: 2, exampleEn: 'Shiny gold', exampleHe: 'זהב מבריק' },
    { englishWord: 'matte', hebrewTranslation: 'מט', category: 'Colors', difficulty: 2, exampleEn: 'Matte finish', exampleHe: 'גימור מט' },
    { englishWord: 'glossy', hebrewTranslation: 'מבריק', category: 'Colors', difficulty: 2, exampleEn: 'Glossy surface', exampleHe: 'משטח מבריק' },
    { englishWord: 'dull', hebrewTranslation: 'מעומעם', category: 'Colors', difficulty: 2, exampleEn: 'Dull color', exampleHe: 'צבע מעומעם' },
    { englishWord: 'rich', hebrewTranslation: 'עשיר', category: 'Colors', difficulty: 2, exampleEn: 'Rich purple', exampleHe: 'סגול עשיר' },
    { englishWord: 'faded', hebrewTranslation: 'דהוי', category: 'Colors', difficulty: 2, exampleEn: 'Faded jeans', exampleHe: 'ג\'ינס דהוי' },
    { englishWord: 'vibrant', hebrewTranslation: 'חי', category: 'Colors', difficulty: 2, exampleEn: 'Vibrant orange', exampleHe: 'כתום חי' },
    { englishWord: 'subtle', hebrewTranslation: 'עדין', category: 'Colors', difficulty: 2, exampleEn: 'Subtle shade', exampleHe: 'גוון עדין' },
    { englishWord: 'bold', hebrewTranslation: 'מודגש', category: 'Colors', difficulty: 2, exampleEn: 'Bold color', exampleHe: 'צבע מודגש' },
    { englishWord: 'transparent', hebrewTranslation: 'שקוף', category: 'Colors', difficulty: 2, exampleEn: 'Transparent glass', exampleHe: 'זכוכית שקופה' },

    // Food category (20 words)
    { englishWord: 'apple', hebrewTranslation: 'תפוח', category: 'Food', difficulty: 1, exampleEn: 'I eat an apple', exampleHe: 'אני אוכל תפוח' },
    { englishWord: 'banana', hebrewTranslation: 'בננה', category: 'Food', difficulty: 1, exampleEn: 'Bananas are yellow', exampleHe: 'בננות צהובות' },
    { englishWord: 'bread', hebrewTranslation: 'לחם', category: 'Food', difficulty: 1, exampleEn: 'Buy bread', exampleHe: 'קנה לחם' },
    { englishWord: 'milk', hebrewTranslation: 'חלב', category: 'Food', difficulty: 1, exampleEn: 'Drink milk', exampleHe: 'שתה חלב' },
    { englishWord: 'water', hebrewTranslation: 'מים', category: 'Food', difficulty: 1, exampleEn: 'I drink water', exampleHe: 'אני שותה מים' },
    { englishWord: 'egg', hebrewTranslation: 'ביצה', category: 'Food', difficulty: 1, exampleEn: 'Eat an egg', exampleHe: 'אכול ביצה' },
    { englishWord: 'cheese', hebrewTranslation: 'גבינה', category: 'Food', difficulty: 1, exampleEn: 'I like cheese', exampleHe: 'אני אוהב גבינה' },
    { englishWord: 'orange', hebrewTranslation: 'תפוז', category: 'Food', difficulty: 1, exampleEn: 'The orange is sweet', exampleHe: 'התפוז מתוק' },
    { englishWord: 'tomato', hebrewTranslation: 'עגבניה', category: 'Food', difficulty: 1, exampleEn: 'Red tomato', exampleHe: 'עגבניה אדומה' },
    { englishWord: 'carrot', hebrewTranslation: 'גזר', category: 'Food', difficulty: 1, exampleEn: 'Rabbits eat carrots', exampleHe: 'ארנבים אוכלים גזר' },
    { englishWord: 'chicken', hebrewTranslation: 'עוף', category: 'Food', difficulty: 1, exampleEn: 'I eat chicken', exampleHe: 'אני אוכל עוף' },
    { englishWord: 'rice', hebrewTranslation: 'אורז', category: 'Food', difficulty: 1, exampleEn: 'Rice is white', exampleHe: 'אורז לבן' },
    { englishWord: 'pasta', hebrewTranslation: 'פסטה', category: 'Food', difficulty: 1, exampleEn: 'I love pasta', exampleHe: 'אני אוהב פסטה' },
    { englishWord: 'cake', hebrewTranslation: 'עוגה', category: 'Food', difficulty: 1, exampleEn: 'Happy birthday cake', exampleHe: 'עוגת יום הולדת' },
    { englishWord: 'cookie', hebrewTranslation: 'עוגייה', category: 'Food', difficulty: 1, exampleEn: 'Chocolate cookie', exampleHe: 'עוגיית שוקולד' },
    { englishWord: 'juice', hebrewTranslation: 'מיץ', category: 'Food', difficulty: 1, exampleEn: 'Orange juice', exampleHe: 'מיץ תפוזים' },
    { englishWord: 'sandwich', hebrewTranslation: 'כריך', category: 'Food', difficulty: 1, exampleEn: 'I make a sandwich', exampleHe: 'אני מכין כריך' },
    { englishWord: 'pizza', hebrewTranslation: 'פיצה', category: 'Food', difficulty: 1, exampleEn: 'I like pizza', exampleHe: 'אני אוהב פיצה' },
    { englishWord: 'ice cream', hebrewTranslation: 'גלידה', category: 'Food', difficulty: 1, exampleEn: 'Cold ice cream', exampleHe: 'גלידה קרה' },
    { englishWord: 'strawberry', hebrewTranslation: 'תות', category: 'Food', difficulty: 1, exampleEn: 'Red strawberry', exampleHe: 'תות אדום' },
    
    // Food category Level 3 (difficulty 2) - 20 words - simpler words
    { englishWord: 'cookie', hebrewTranslation: 'עוגייה', category: 'Food', difficulty: 2, exampleEn: 'Chocolate cookie', exampleHe: 'עוגיית שוקולד' },
    { englishWord: 'cake', hebrewTranslation: 'עוגה', category: 'Food', difficulty: 2, exampleEn: 'Birthday cake', exampleHe: 'עוגת יום הולדת' },
    { englishWord: 'candy', hebrewTranslation: 'ממתק', category: 'Food', difficulty: 2, exampleEn: 'Sweet candy', exampleHe: 'ממתק מתוק' },
    { englishWord: 'ice', hebrewTranslation: 'קרח', category: 'Food', difficulty: 2, exampleEn: 'Ice in water', exampleHe: 'קרח במים' },
    { englishWord: 'juice', hebrewTranslation: 'מיץ', category: 'Food', difficulty: 2, exampleEn: 'Orange juice', exampleHe: 'מיץ תפוזים' },
    { englishWord: 'soup', hebrewTranslation: 'מרק', category: 'Food', difficulty: 2, exampleEn: 'Hot soup', exampleHe: 'מרק חם' },
    { englishWord: 'salad', hebrewTranslation: 'סלט', category: 'Food', difficulty: 2, exampleEn: 'Fresh salad', exampleHe: 'סלט טרי' },
    { englishWord: 'sandwich', hebrewTranslation: 'כריך', category: 'Food', difficulty: 2, exampleEn: 'Cheese sandwich', exampleHe: 'כריך גבינה' },
    { englishWord: 'pizza', hebrewTranslation: 'פיצה', category: 'Food', difficulty: 2, exampleEn: 'Pizza slice', exampleHe: 'פרוסת פיצה' },
    { englishWord: 'burger', hebrewTranslation: 'המבורגר', category: 'Food', difficulty: 2, exampleEn: 'Cheese burger', exampleHe: 'המבורגר עם גבינה' },
    { englishWord: 'fries', hebrewTranslation: 'צ\'יפס', category: 'Food', difficulty: 2, exampleEn: 'French fries', exampleHe: 'צ\'יפס' },
    { englishWord: 'cereal', hebrewTranslation: 'דגנים', category: 'Food', difficulty: 2, exampleEn: 'Breakfast cereal', exampleHe: 'דגני בוקר' },
    { englishWord: 'yogurt', hebrewTranslation: 'יוגורט', category: 'Food', difficulty: 2, exampleEn: 'Strawberry yogurt', exampleHe: 'יוגורט תות' },
    { englishWord: 'honey', hebrewTranslation: 'דבש', category: 'Food', difficulty: 2, exampleEn: 'Sweet honey', exampleHe: 'דבש מתוק' },
    { englishWord: 'jam', hebrewTranslation: 'ריבה', category: 'Food', difficulty: 2, exampleEn: 'Strawberry jam', exampleHe: 'ריבת תות' },
    { englishWord: 'butter', hebrewTranslation: 'חמאה', category: 'Food', difficulty: 2, exampleEn: 'Bread with butter', exampleHe: 'לחם עם חמאה' },
    { englishWord: 'sugar', hebrewTranslation: 'סוכר', category: 'Food', difficulty: 2, exampleEn: 'Add sugar', exampleHe: 'הוסף סוכר' },
    { englishWord: 'salt', hebrewTranslation: 'מלח', category: 'Food', difficulty: 2, exampleEn: 'Add salt', exampleHe: 'הוסף מלח' },
    { englishWord: 'pepper', hebrewTranslation: 'פלפל', category: 'Food', difficulty: 2, exampleEn: 'Black pepper', exampleHe: 'פלפל שחור' },
    { englishWord: 'oil', hebrewTranslation: 'שמן', category: 'Food', difficulty: 2, exampleEn: 'Cooking oil', exampleHe: 'שמן בישול' },


    // Body Parts (20 words)
    { englishWord: 'head', hebrewTranslation: 'ראש', category: 'Body', difficulty: 1, exampleEn: 'My head hurts', exampleHe: 'הראש שלי כואב' },
    { englishWord: 'eye', hebrewTranslation: 'עין', category: 'Body', difficulty: 1, exampleEn: 'I have two eyes', exampleHe: 'יש לי שתי עיניים' },
    { englishWord: 'nose', hebrewTranslation: 'אף', category: 'Body', difficulty: 1, exampleEn: 'I smell with my nose', exampleHe: 'אני מריח עם האף שלי' },
    { englishWord: 'mouth', hebrewTranslation: 'פה', category: 'Body', difficulty: 1, exampleEn: 'Open your mouth', exampleHe: 'פתח את הפה' },
    { englishWord: 'hand', hebrewTranslation: 'יד', category: 'Body', difficulty: 1, exampleEn: 'Raise your hand', exampleHe: 'הרם את היד' },
    { englishWord: 'foot', hebrewTranslation: 'רגל', category: 'Body', difficulty: 1, exampleEn: 'I walk with my feet', exampleHe: 'אני הולך עם הרגליים' },
    { englishWord: 'arm', hebrewTranslation: 'זרוע', category: 'Body', difficulty: 1, exampleEn: 'My arm is strong', exampleHe: 'הזרוע שלי חזקה' },
    { englishWord: 'leg', hebrewTranslation: 'רגל', category: 'Body', difficulty: 1, exampleEn: 'I run with my legs', exampleHe: 'אני רץ עם הרגליים' },
    { englishWord: 'finger', hebrewTranslation: 'אצבע', category: 'Body', difficulty: 1, exampleEn: 'I have ten fingers', exampleHe: 'יש לי עשר אצבעות' },
    { englishWord: 'tooth', hebrewTranslation: 'שן', category: 'Body', difficulty: 1, exampleEn: 'Brush your teeth', exampleHe: 'צחצח שיניים' },
    { englishWord: 'ear', hebrewTranslation: 'אוזן', category: 'Body', difficulty: 1, exampleEn: 'I hear with my ears', exampleHe: 'אני שומע עם האוזניים' },
    { englishWord: 'hair', hebrewTranslation: 'שיער', category: 'Body', difficulty: 1, exampleEn: 'Brush your hair', exampleHe: 'סרק את השיער' },
    { englishWord: 'face', hebrewTranslation: 'פנים', category: 'Body', difficulty: 1, exampleEn: 'Wash your face', exampleHe: 'שטוף את הפנים' },
    { englishWord: 'neck', hebrewTranslation: 'צוואר', category: 'Body', difficulty: 1, exampleEn: 'My neck hurts', exampleHe: 'הצוואר שלי כואב' },
    { englishWord: 'shoulder', hebrewTranslation: 'כתף', category: 'Body', difficulty: 1, exampleEn: 'My shoulder is strong', exampleHe: 'הכתף שלי חזקה' },
    { englishWord: 'knee', hebrewTranslation: 'ברך', category: 'Body', difficulty: 1, exampleEn: 'Bend your knee', exampleHe: 'כופף את הברך' },
    { englishWord: 'elbow', hebrewTranslation: 'מרפק', category: 'Body', difficulty: 1, exampleEn: 'My elbow hurts', exampleHe: 'המרפק שלי כואב' },
    { englishWord: 'back', hebrewTranslation: 'גב', category: 'Body', difficulty: 1, exampleEn: 'My back is straight', exampleHe: 'הגב שלי ישר' },
    { englishWord: 'chest', hebrewTranslation: 'חזה', category: 'Body', difficulty: 1, exampleEn: 'My chest is strong', exampleHe: 'החזה שלי חזק' },
    { englishWord: 'stomach', hebrewTranslation: 'בטן', category: 'Body', difficulty: 1, exampleEn: 'My stomach is full', exampleHe: 'הבטן שלי מלאה' },
    
    // Body category Level 3 (difficulty 2) - 20 words - simpler words
    { englishWord: 'thumb', hebrewTranslation: 'אגודל', category: 'Body', difficulty: 2, exampleEn: 'Thumbs up', exampleHe: 'אגודל למעלה' },
    { englishWord: 'toe', hebrewTranslation: 'בוהן', category: 'Body', difficulty: 2, exampleEn: 'Big toe', exampleHe: 'בוהן גדולה' },
    { englishWord: 'nail', hebrewTranslation: 'ציפורן', category: 'Body', difficulty: 2, exampleEn: 'Cut your nails', exampleHe: 'גזור את הציפורניים' },
    { englishWord: 'palm', hebrewTranslation: 'כף יד', category: 'Body', difficulty: 2, exampleEn: 'Open palm', exampleHe: 'כף יד פתוחה' },
    { englishWord: 'wrist', hebrewTranslation: 'שורש כף יד', category: 'Body', difficulty: 2, exampleEn: 'Watch on wrist', exampleHe: 'שעון על שורש כף היד' },
    { englishWord: 'waist', hebrewTranslation: 'מותן', category: 'Body', difficulty: 2, exampleEn: 'Small waist', exampleHe: 'מותן קטן' },
    { englishWord: 'hip', hebrewTranslation: 'ירך', category: 'Body', difficulty: 2, exampleEn: 'Hip bone', exampleHe: 'עצם ירך' },
    { englishWord: 'thigh', hebrewTranslation: 'ירך עליונה', category: 'Body', difficulty: 2, exampleEn: 'Strong thigh', exampleHe: 'ירך עליונה חזקה' },
    { englishWord: 'ankle', hebrewTranslation: 'קרסול', category: 'Body', difficulty: 2, exampleEn: 'Twisted ankle', exampleHe: 'קרסול מעוקם' },
    { englishWord: 'heel', hebrewTranslation: 'עקב', category: 'Body', difficulty: 2, exampleEn: 'High heel', exampleHe: 'עקב גבוה' },
    { englishWord: 'sole', hebrewTranslation: 'כף רגל', category: 'Body', difficulty: 2, exampleEn: 'Sole of foot', exampleHe: 'כף הרגל' },
    { englishWord: 'chin', hebrewTranslation: 'סנטר', category: 'Body', difficulty: 2, exampleEn: 'Pointed chin', exampleHe: 'סנטר מחודד' },
    { englishWord: 'cheek', hebrewTranslation: 'לחי', category: 'Body', difficulty: 2, exampleEn: 'Rosy cheeks', exampleHe: 'לחיים ורודות' },
    { englishWord: 'forehead', hebrewTranslation: 'מצח', category: 'Body', difficulty: 2, exampleEn: 'Wide forehead', exampleHe: 'מצח רחב' },
    { englishWord: 'eyebrow', hebrewTranslation: 'גבה', category: 'Body', difficulty: 2, exampleEn: 'Thick eyebrow', exampleHe: 'גבה עבה' },
    { englishWord: 'eyelash', hebrewTranslation: 'ריס', category: 'Body', difficulty: 2, exampleEn: 'Long eyelash', exampleHe: 'ריס ארוך' },
    { englishWord: 'lip', hebrewTranslation: 'שפה', category: 'Body', difficulty: 2, exampleEn: 'Red lip', exampleHe: 'שפה אדומה' },
    { englishWord: 'tongue', hebrewTranslation: 'לשון', category: 'Body', difficulty: 2, exampleEn: 'Stick out tongue', exampleHe: 'הוצא לשון' },
    { englishWord: 'teeth', hebrewTranslation: 'שיניים', category: 'Body', difficulty: 2, exampleEn: 'Brush your teeth', exampleHe: 'צחצח שיניים' },
    { englishWord: 'gum', hebrewTranslation: 'חניכיים', category: 'Body', difficulty: 2, exampleEn: 'Healthy gums', exampleHe: 'חניכיים בריאות' },

    // Family (20 words)
    { englishWord: 'mother', hebrewTranslation: 'אמא', category: 'Family', difficulty: 1, exampleEn: 'I love my mother', exampleHe: 'אני אוהב את אמא שלי' },
    { englishWord: 'father', hebrewTranslation: 'אבא', category: 'Family', difficulty: 1, exampleEn: 'My father is tall', exampleHe: 'אבא שלי גבוה' },
    { englishWord: 'sister', hebrewTranslation: 'אחות', category: 'Family', difficulty: 1, exampleEn: 'My sister is nice', exampleHe: 'האחות שלי נחמדה' },
    { englishWord: 'brother', hebrewTranslation: 'אח', category: 'Family', difficulty: 1, exampleEn: 'My brother plays soccer', exampleHe: 'האח שלי משחק כדורגל' },
    { englishWord: 'grandmother', hebrewTranslation: 'סבתא', category: 'Family', difficulty: 1, exampleEn: 'Grandmother bakes cookies', exampleHe: 'סבתא אופה עוגיות' },
    { englishWord: 'grandfather', hebrewTranslation: 'סבא', category: 'Family', difficulty: 1, exampleEn: 'Grandfather tells stories', exampleHe: 'סבא מספר סיפורים' },
    { englishWord: 'baby', hebrewTranslation: 'תינוק', category: 'Family', difficulty: 1, exampleEn: 'The baby is sleeping', exampleHe: 'התינוק ישן' },
    { englishWord: 'uncle', hebrewTranslation: 'דוד', category: 'Family', difficulty: 1, exampleEn: 'My uncle is funny', exampleHe: 'הדוד שלי מצחיק' },
    { englishWord: 'aunt', hebrewTranslation: 'דודה', category: 'Family', difficulty: 1, exampleEn: 'My aunt is kind', exampleHe: 'הדודה שלי נחמדה' },
    { englishWord: 'cousin', hebrewTranslation: 'בן דוד', category: 'Family', difficulty: 1, exampleEn: 'My cousin is my friend', exampleHe: 'בן הדוד שלי הוא החבר שלי' },
    { englishWord: 'son', hebrewTranslation: 'בן', category: 'Family', difficulty: 1, exampleEn: 'My son is smart', exampleHe: 'הבן שלי חכם' },
    { englishWord: 'daughter', hebrewTranslation: 'בת', category: 'Family', difficulty: 1, exampleEn: 'My daughter is beautiful', exampleHe: 'הבת שלי יפה' },
    { englishWord: 'parents', hebrewTranslation: 'הורים', category: 'Family', difficulty: 1, exampleEn: 'I love my parents', exampleHe: 'אני אוהב את ההורים שלי' },
    { englishWord: 'grandparents', hebrewTranslation: 'סבא וסבתא', category: 'Family', difficulty: 1, exampleEn: 'I visit my grandparents', exampleHe: 'אני מבקר את סבא וסבתא' },
    { englishWord: 'twin', hebrewTranslation: 'תאום', category: 'Family', difficulty: 1, exampleEn: 'My twin is my best friend', exampleHe: 'התאום שלי הוא החבר הכי טוב שלי' },
    { englishWord: 'nephew', hebrewTranslation: 'אחיין', category: 'Family', difficulty: 1, exampleEn: 'My nephew is cute', exampleHe: 'האחיין שלי חמוד' },
    { englishWord: 'niece', hebrewTranslation: 'אחיינית', category: 'Family', difficulty: 1, exampleEn: 'My niece is smart', exampleHe: 'האחיינית שלי חכמה' },
    { englishWord: 'husband', hebrewTranslation: 'בעל', category: 'Family', difficulty: 1, exampleEn: 'My husband is kind', exampleHe: 'הבעל שלי נחמד' },
    { englishWord: 'wife', hebrewTranslation: 'אישה', category: 'Family', difficulty: 1, exampleEn: 'My wife is beautiful', exampleHe: 'האישה שלי יפה' },
    { englishWord: 'baby', hebrewTranslation: 'תינוק', category: 'Family', difficulty: 2, exampleEn: 'Cute baby', exampleHe: 'תינוק חמוד' },
    { englishWord: 'toddler', hebrewTranslation: 'פעוט', category: 'Family', difficulty: 2, exampleEn: 'Little toddler', exampleHe: 'פעוט קטן' },
    { englishWord: 'child', hebrewTranslation: 'ילד', category: 'Family', difficulty: 2, exampleEn: 'Happy child', exampleHe: 'ילד שמח' },
    { englishWord: 'teen', hebrewTranslation: 'נער', category: 'Family', difficulty: 2, exampleEn: 'Teenager', exampleHe: 'נער' },
    { englishWord: 'adult', hebrewTranslation: 'מבוגר', category: 'Family', difficulty: 2, exampleEn: 'Responsible adult', exampleHe: 'מבוגר אחראי' },
    { englishWord: 'elder', hebrewTranslation: 'קשיש', category: 'Family', difficulty: 2, exampleEn: 'Wise elder', exampleHe: 'קשיש חכם' },
    { englishWord: 'twin', hebrewTranslation: 'תאום', category: 'Family', difficulty: 2, exampleEn: 'Twin brother', exampleHe: 'אח תאום' },
    { englishWord: 'cousin', hebrewTranslation: 'בן דוד', category: 'Family', difficulty: 2, exampleEn: 'My cousin', exampleHe: 'בן הדוד שלי' },
    { englishWord: 'nephew', hebrewTranslation: 'אחיין', category: 'Family', difficulty: 2, exampleEn: 'My nephew', exampleHe: 'האחיין שלי' },
    { englishWord: 'niece', hebrewTranslation: 'אחיינית', category: 'Family', difficulty: 2, exampleEn: 'My niece', exampleHe: 'האחיינית שלי' },
    { englishWord: 'uncle', hebrewTranslation: 'דוד', category: 'Family', difficulty: 2, exampleEn: 'My uncle', exampleHe: 'הדוד שלי' },
    { englishWord: 'aunt', hebrewTranslation: 'דודה', category: 'Family', difficulty: 2, exampleEn: 'My aunt', exampleHe: 'הדודה שלי' },
    { englishWord: 'grandson', hebrewTranslation: 'נכד', category: 'Family', difficulty: 2, exampleEn: 'My grandson', exampleHe: 'הנכד שלי' },
    { englishWord: 'granddaughter', hebrewTranslation: 'נכדה', category: 'Family', difficulty: 2, exampleEn: 'My granddaughter', exampleHe: 'הנכדה שלי' },
    { englishWord: 'grandpa', hebrewTranslation: 'סבא', category: 'Family', difficulty: 2, exampleEn: 'My grandpa', exampleHe: 'הסבא שלי' },
    { englishWord: 'grandma', hebrewTranslation: 'סבתא', category: 'Family', difficulty: 2, exampleEn: 'My grandma', exampleHe: 'הסבתא שלי' },
    { englishWord: 'husband', hebrewTranslation: 'בעל', category: 'Family', difficulty: 2, exampleEn: 'My husband', exampleHe: 'הבעל שלי' },
    { englishWord: 'wife', hebrewTranslation: 'אישה', category: 'Family', difficulty: 2, exampleEn: 'My wife', exampleHe: 'האישה שלי' },
    { englishWord: 'parent', hebrewTranslation: 'הורה', category: 'Family', difficulty: 2, exampleEn: 'Good parent', exampleHe: 'הורה טוב' },
    { englishWord: 'guardian', hebrewTranslation: 'אפוטרופוס', category: 'Family', difficulty: 2, exampleEn: 'Legal guardian', exampleHe: 'אפוטרופוס חוקי' },
    { englishWord: 'child', hebrewTranslation: 'ילד', category: 'Family', difficulty: 1, exampleEn: 'The child is playing', exampleHe: 'הילד משחק' },

    // Actions/Verbs
    { englishWord: 'run', hebrewTranslation: 'לרוץ', category: 'Actions', difficulty: 1, exampleEn: 'I run fast', exampleHe: 'אני רץ מהר' },
    { englishWord: 'jump', hebrewTranslation: 'לקפוץ', category: 'Actions', difficulty: 1, exampleEn: 'Jump high', exampleHe: 'קפוץ גבוה' },
    { englishWord: 'walk', hebrewTranslation: 'ללכת', category: 'Actions', difficulty: 1, exampleEn: 'I walk to school', exampleHe: 'אני הולך לבית ספר' },
    { englishWord: 'sit', hebrewTranslation: 'לשבת', category: 'Actions', difficulty: 1, exampleEn: 'Sit down', exampleHe: 'שב' },
    { englishWord: 'stand', hebrewTranslation: 'לעמוד', category: 'Actions', difficulty: 1, exampleEn: 'Stand up', exampleHe: 'עמוד' },
    { englishWord: 'eat', hebrewTranslation: 'לאכול', category: 'Actions', difficulty: 1, exampleEn: 'I eat breakfast', exampleHe: 'אני אוכל ארוחת בוקר' },
    { englishWord: 'drink', hebrewTranslation: 'לשתות', category: 'Actions', difficulty: 1, exampleEn: 'Drink water', exampleHe: 'שתה מים' },
    { englishWord: 'sleep', hebrewTranslation: 'לישון', category: 'Actions', difficulty: 1, exampleEn: 'I sleep at night', exampleHe: 'אני ישן בלילה' },
    { englishWord: 'play', hebrewTranslation: 'לשחק', category: 'Actions', difficulty: 1, exampleEn: 'I play outside', exampleHe: 'אני משחק בחוץ' },
    { englishWord: 'read', hebrewTranslation: 'לקרוא', category: 'Actions', difficulty: 1, exampleEn: 'I read books', exampleHe: 'אני קורא ספרים' },
    { englishWord: 'write', hebrewTranslation: 'לכתוב', category: 'Actions', difficulty: 1, exampleEn: 'Write your name', exampleHe: 'כתוב את השם שלך' },
    { englishWord: 'draw', hebrewTranslation: 'לצייר', category: 'Actions', difficulty: 1, exampleEn: 'I draw pictures', exampleHe: 'אני מצייר תמונות' },
    { englishWord: 'sing', hebrewTranslation: 'לשיר', category: 'Actions', difficulty: 1, exampleEn: 'Sing a song', exampleHe: 'שיר שיר' },
    { englishWord: 'dance', hebrewTranslation: 'לרקוד', category: 'Actions', difficulty: 1, exampleEn: 'I love to dance', exampleHe: 'אני אוהב לרקוד' },

    // Nature (20 words)
    { englishWord: 'tree', hebrewTranslation: 'עץ', category: 'Nature', difficulty: 1, exampleEn: 'The tree is tall', exampleHe: 'העץ גבוה' },
    { englishWord: 'flower', hebrewTranslation: 'פרח', category: 'Nature', difficulty: 1, exampleEn: 'Beautiful flower', exampleHe: 'פרח יפה' },
    { englishWord: 'grass', hebrewTranslation: 'דשא', category: 'Nature', difficulty: 1, exampleEn: 'Green grass', exampleHe: 'דשא ירוק' },
    { englishWord: 'sun', hebrewTranslation: 'שמש', category: 'Nature', difficulty: 1, exampleEn: 'The sun is bright', exampleHe: 'השמש בוהקת' },
    { englishWord: 'moon', hebrewTranslation: 'ירח', category: 'Nature', difficulty: 1, exampleEn: 'The moon is round', exampleHe: 'הירח עגול' },
    { englishWord: 'star', hebrewTranslation: 'כוכב', category: 'Nature', difficulty: 1, exampleEn: 'Stars in the sky', exampleHe: 'כוכבים בשמיים' },
    { englishWord: 'cloud', hebrewTranslation: 'ענן', category: 'Nature', difficulty: 1, exampleEn: 'White cloud', exampleHe: 'ענן לבן' },
    { englishWord: 'rain', hebrewTranslation: 'גשם', category: 'Nature', difficulty: 1, exampleEn: 'It is raining', exampleHe: 'יורד גשם' },
    { englishWord: 'snow', hebrewTranslation: 'שלג', category: 'Nature', difficulty: 1, exampleEn: 'White snow', exampleHe: 'שלג לבן' },
    { englishWord: 'wind', hebrewTranslation: 'רוח', category: 'Nature', difficulty: 1, exampleEn: 'Strong wind', exampleHe: 'רוח חזקה' },
    { englishWord: 'mountain', hebrewTranslation: 'הר', category: 'Nature', difficulty: 1, exampleEn: 'The mountain is high', exampleHe: 'ההר גבוה' },
    { englishWord: 'river', hebrewTranslation: 'נהר', category: 'Nature', difficulty: 1, exampleEn: 'The river flows', exampleHe: 'הנהר זורם' },
    { englishWord: 'ocean', hebrewTranslation: 'אוקיינוס', category: 'Nature', difficulty: 1, exampleEn: 'The ocean is big', exampleHe: 'האוקיינוס גדול' },
    { englishWord: 'lake', hebrewTranslation: 'אגם', category: 'Nature', difficulty: 1, exampleEn: 'The lake is calm', exampleHe: 'האגם שקט' },
    { englishWord: 'forest', hebrewTranslation: 'יער', category: 'Nature', difficulty: 1, exampleEn: 'The forest is dark', exampleHe: 'היער חשוך' },
    { englishWord: 'grass', hebrewTranslation: 'דשא', category: 'Nature', difficulty: 2, exampleEn: 'Green grass', exampleHe: 'דשא ירוק' },
    { englishWord: 'flower', hebrewTranslation: 'פרח', category: 'Nature', difficulty: 2, exampleEn: 'Beautiful flower', exampleHe: 'פרח יפה' },
    { englishWord: 'tree', hebrewTranslation: 'עץ', category: 'Nature', difficulty: 2, exampleEn: 'Tall tree', exampleHe: 'עץ גבוה' },
    { englishWord: 'leaf', hebrewTranslation: 'עלה', category: 'Nature', difficulty: 2, exampleEn: 'Green leaf', exampleHe: 'עלה ירוק' },
    { englishWord: 'branch', hebrewTranslation: 'ענף', category: 'Nature', difficulty: 2, exampleEn: 'Tree branch', exampleHe: 'ענף עץ' },
    { englishWord: 'root', hebrewTranslation: 'שורש', category: 'Nature', difficulty: 2, exampleEn: 'Tree root', exampleHe: 'שורש עץ' },
    { englishWord: 'seed', hebrewTranslation: 'זרע', category: 'Nature', difficulty: 2, exampleEn: 'Plant a seed', exampleHe: 'זרע זרע' },
    { englishWord: 'bud', hebrewTranslation: 'ניצן', category: 'Nature', difficulty: 2, exampleEn: 'Flower bud', exampleHe: 'ניצן פרח' },
    { englishWord: 'stem', hebrewTranslation: 'גבעול', category: 'Nature', difficulty: 2, exampleEn: 'Plant stem', exampleHe: 'גבעול צמח' },
    { englishWord: 'petal', hebrewTranslation: 'עלה כותרת', category: 'Nature', difficulty: 2, exampleEn: 'Rose petal', exampleHe: 'עלה כותרת ורד' },
    { englishWord: 'thorn', hebrewTranslation: 'קוץ', category: 'Nature', difficulty: 2, exampleEn: 'Rose thorn', exampleHe: 'קוץ ורד' },
    { englishWord: 'bark', hebrewTranslation: 'קליפה', category: 'Nature', difficulty: 2, exampleEn: 'Tree bark', exampleHe: 'קליפת עץ' },
    { englishWord: 'trunk', hebrewTranslation: 'גזע', category: 'Nature', difficulty: 2, exampleEn: 'Tree trunk', exampleHe: 'גזע עץ' },
    { englishWord: 'moss', hebrewTranslation: 'טחב', category: 'Nature', difficulty: 2, exampleEn: 'Green moss', exampleHe: 'טחב ירוק' },
    { englishWord: 'fern', hebrewTranslation: 'שרך', category: 'Nature', difficulty: 2, exampleEn: 'Green fern', exampleHe: 'שרך ירוק' },
    { englishWord: 'bush', hebrewTranslation: 'שיח', category: 'Nature', difficulty: 2, exampleEn: 'Green bush', exampleHe: 'שיח ירוק' },
    { englishWord: 'vine', hebrewTranslation: 'גפן', category: 'Nature', difficulty: 2, exampleEn: 'Grape vine', exampleHe: 'גפן ענבים' },
    { englishWord: 'weed', hebrewTranslation: 'עשב שוטה', category: 'Nature', difficulty: 2, exampleEn: 'Pull weeds', exampleHe: 'עקור עשבים שוטים' },
    { englishWord: 'sprout', hebrewTranslation: 'נבט', category: 'Nature', difficulty: 2, exampleEn: 'New sprout', exampleHe: 'נבט חדש' },
    { englishWord: 'bloom', hebrewTranslation: 'פרח', category: 'Nature', difficulty: 2, exampleEn: 'Flower blooms', exampleHe: 'הפרח פורח' },
    { englishWord: 'leaf', hebrewTranslation: 'עלה', category: 'Nature', difficulty: 1, exampleEn: 'Green leaf', exampleHe: 'עלה ירוק' },
    { englishWord: 'rock', hebrewTranslation: 'סלע', category: 'Nature', difficulty: 1, exampleEn: 'Big rock', exampleHe: 'סלע גדול' },
    { englishWord: 'sand', hebrewTranslation: 'חול', category: 'Nature', difficulty: 1, exampleEn: 'Yellow sand', exampleHe: 'חול צהוב' },
    { englishWord: 'beach', hebrewTranslation: 'חוף', category: 'Nature', difficulty: 1, exampleEn: 'I play on the beach', exampleHe: 'אני משחק בחוף' },
    { englishWord: 'sky', hebrewTranslation: 'שמיים', category: 'Nature', difficulty: 1, exampleEn: 'Blue sky', exampleHe: 'שמיים כחולים' },

    // Numbers
    { englishWord: 'one', hebrewTranslation: 'אחד', category: 'Numbers', difficulty: 1, exampleEn: 'One apple', exampleHe: 'תפוח אחד' },
    { englishWord: 'two', hebrewTranslation: 'שניים', category: 'Numbers', difficulty: 1, exampleEn: 'Two books', exampleHe: 'שני ספרים' },
    { englishWord: 'three', hebrewTranslation: 'שלושה', category: 'Numbers', difficulty: 1, exampleEn: 'Three cats', exampleHe: 'שלושה חתולים' },
    { englishWord: 'four', hebrewTranslation: 'ארבעה', category: 'Numbers', difficulty: 1, exampleEn: 'Four chairs', exampleHe: 'ארבעה כיסאות' },
    { englishWord: 'five', hebrewTranslation: 'חמישה', category: 'Numbers', difficulty: 1, exampleEn: 'Five fingers', exampleHe: 'חמש אצבעות' },
    { englishWord: 'ten', hebrewTranslation: 'עשרה', category: 'Numbers', difficulty: 1, exampleEn: 'Ten students', exampleHe: 'עשרה תלמידים' },

    // Time
    { englishWord: 'morning', hebrewTranslation: 'בוקר', category: 'Time', difficulty: 1, exampleEn: 'Good morning', exampleHe: 'בוקר טוב' },
    { englishWord: 'afternoon', hebrewTranslation: 'צהריים', category: 'Time', difficulty: 1, exampleEn: 'Good afternoon', exampleHe: 'צהריים טובים' },
    { englishWord: 'evening', hebrewTranslation: 'ערב', category: 'Time', difficulty: 1, exampleEn: 'Good evening', exampleHe: 'ערב טוב' },
    { englishWord: 'night', hebrewTranslation: 'לילה', category: 'Time', difficulty: 1, exampleEn: 'Good night', exampleHe: 'לילה טוב' },
    { englishWord: 'today', hebrewTranslation: 'היום', category: 'Time', difficulty: 1, exampleEn: 'Today is Monday', exampleHe: 'היום יום שני' },
    { englishWord: 'tomorrow', hebrewTranslation: 'מחר', category: 'Time', difficulty: 1, exampleEn: 'See you tomorrow', exampleHe: 'נתראה מחר' },
    { englishWord: 'yesterday', hebrewTranslation: 'אתמול', category: 'Time', difficulty: 1, exampleEn: 'Yesterday was fun', exampleHe: 'אתמול היה כיף' },

    // Clothing (20 words)
    { englishWord: 'shirt', hebrewTranslation: 'חולצה', category: 'Clothes', difficulty: 1, exampleEn: 'Blue shirt', exampleHe: 'חולצה כחולה' },
    { englishWord: 'pants', hebrewTranslation: 'מכנסיים', category: 'Clothes', difficulty: 1, exampleEn: 'Black pants', exampleHe: 'מכנסיים שחורים' },
    { englishWord: 'shoes', hebrewTranslation: 'נעליים', category: 'Clothes', difficulty: 1, exampleEn: 'New shoes', exampleHe: 'נעליים חדשות' },
    { englishWord: 'hat', hebrewTranslation: 'כובע', category: 'Clothes', difficulty: 1, exampleEn: 'Wear a hat', exampleHe: 'חבוש כובע' },
    { englishWord: 'dress', hebrewTranslation: 'שמלה', category: 'Clothes', difficulty: 1, exampleEn: 'Beautiful dress', exampleHe: 'שמלה יפה' },
    { englishWord: 'socks', hebrewTranslation: 'גרביים', category: 'Clothes', difficulty: 1, exampleEn: 'Warm socks', exampleHe: 'גרביים חמות' },
    { englishWord: 'jacket', hebrewTranslation: 'מעיל', category: 'Clothes', difficulty: 1, exampleEn: 'Warm jacket', exampleHe: 'מעיל חם' },
    { englishWord: 'coat', hebrewTranslation: 'מעיל', category: 'Clothes', difficulty: 1, exampleEn: 'Winter coat', exampleHe: 'מעיל חורף' },
    { englishWord: 'sweater', hebrewTranslation: 'סוודר', category: 'Clothes', difficulty: 1, exampleEn: 'Wool sweater', exampleHe: 'סוודר צמר' },
    { englishWord: 't-shirt', hebrewTranslation: 'חולצת טי', category: 'Clothes', difficulty: 1, exampleEn: 'White t-shirt', exampleHe: 'חולצת טי לבנה' },
    { englishWord: 'shorts', hebrewTranslation: 'מכנסיים קצרים', category: 'Clothes', difficulty: 1, exampleEn: 'Summer shorts', exampleHe: 'מכנסיים קצרים לקיץ' },
    { englishWord: 'skirt', hebrewTranslation: 'חצאית', category: 'Clothes', difficulty: 1, exampleEn: 'Long skirt', exampleHe: 'חצאית ארוכה' },
    { englishWord: 'belt', hebrewTranslation: 'חגורה', category: 'Clothes', difficulty: 1, exampleEn: 'Leather belt', exampleHe: 'חגורה מעור' },
    { englishWord: 'gloves', hebrewTranslation: 'כפפות', category: 'Clothes', difficulty: 1, exampleEn: 'Warm gloves', exampleHe: 'כפפות חמות' },
    { englishWord: 'scarf', hebrewTranslation: 'צעיף', category: 'Clothes', difficulty: 1, exampleEn: 'Wool scarf', exampleHe: 'צעיף צמר' },
    { englishWord: 'boots', hebrewTranslation: 'מגפיים', category: 'Clothes', difficulty: 1, exampleEn: 'Winter boots', exampleHe: 'מגפיים לחורף' },
    { englishWord: 'slippers', hebrewTranslation: 'נעלי בית', category: 'Clothes', difficulty: 1, exampleEn: 'Comfortable slippers', exampleHe: 'נעלי בית נוחות' },
    { englishWord: 'pajamas', hebrewTranslation: 'פיג\'מה', category: 'Clothes', difficulty: 1, exampleEn: 'Warm pajamas', exampleHe: 'פיג\'מה חמה' },
    { englishWord: 'underwear', hebrewTranslation: 'תחתונים', category: 'Clothes', difficulty: 1, exampleEn: 'Clean underwear', exampleHe: 'תחתונים נקיים' },
    { englishWord: 'tie', hebrewTranslation: 'עניבה', category: 'Clothes', difficulty: 1, exampleEn: 'Red tie', exampleHe: 'עניבה אדומה' },
    { englishWord: 'belt', hebrewTranslation: 'חגורה', category: 'Clothes', difficulty: 2, exampleEn: 'Leather belt', exampleHe: 'חגורת עור' },
    { englishWord: 'button', hebrewTranslation: 'כפתור', category: 'Clothes', difficulty: 2, exampleEn: 'Button your shirt', exampleHe: 'כפתר את החולצה' },
    { englishWord: 'zipper', hebrewTranslation: 'רוכסן', category: 'Clothes', difficulty: 2, exampleEn: 'Zip up', exampleHe: 'רוכסן למעלה' },
    { englishWord: 'pocket', hebrewTranslation: 'כיס', category: 'Clothes', difficulty: 2, exampleEn: 'Put in pocket', exampleHe: 'שים בכיס' },
    { englishWord: 'collar', hebrewTranslation: 'צווארון', category: 'Clothes', difficulty: 2, exampleEn: 'Shirt collar', exampleHe: 'צווארון חולצה' },
    { englishWord: 'sleeve', hebrewTranslation: 'שרוול', category: 'Clothes', difficulty: 2, exampleEn: 'Long sleeve', exampleHe: 'שרוול ארוך' },
    { englishWord: 'cuff', hebrewTranslation: 'מפרק', category: 'Clothes', difficulty: 2, exampleEn: 'Shirt cuff', exampleHe: 'מפרק חולצה' },
    { englishWord: 'hem', hebrewTranslation: 'שוליים', category: 'Clothes', difficulty: 2, exampleEn: 'Dress hem', exampleHe: 'שולי שמלה' },
    { englishWord: 'seam', hebrewTranslation: 'תפר', category: 'Clothes', difficulty: 2, exampleEn: 'Sew a seam', exampleHe: 'תפר תפר' },
    { englishWord: 'fabric', hebrewTranslation: 'בד', category: 'Clothes', difficulty: 2, exampleEn: 'Soft fabric', exampleHe: 'בד רך' },
    { englishWord: 'cloth', hebrewTranslation: 'טקסטיל', category: 'Clothes', difficulty: 2, exampleEn: 'Clean cloth', exampleHe: 'טקסטיל נקי' },
    { englishWord: 'thread', hebrewTranslation: 'חוט', category: 'Clothes', difficulty: 2, exampleEn: 'Sewing thread', exampleHe: 'חוט תפירה' },
    { englishWord: 'needle', hebrewTranslation: 'מחט', category: 'Clothes', difficulty: 2, exampleEn: 'Sharp needle', exampleHe: 'מחט חדה' },
    { englishWord: 'pin', hebrewTranslation: 'סיכה', category: 'Clothes', difficulty: 2, exampleEn: 'Safety pin', exampleHe: 'סיכת ביטחון' },
    { englishWord: 'buckle', hebrewTranslation: 'אבזם', category: 'Clothes', difficulty: 2, exampleEn: 'Belt buckle', exampleHe: 'אבזם חגורה' },
    { englishWord: 'lace', hebrewTranslation: 'שרוך', category: 'Clothes', difficulty: 2, exampleEn: 'Shoe lace', exampleHe: 'שרוך נעל' },
    { englishWord: 'strap', hebrewTranslation: 'רצועה', category: 'Clothes', difficulty: 2, exampleEn: 'Bag strap', exampleHe: 'רצועת תיק' },
    { englishWord: 'patch', hebrewTranslation: 'טלאי', category: 'Clothes', difficulty: 2, exampleEn: 'Knee patch', exampleHe: 'טלאי ברך' },
    { englishWord: 'tag', hebrewTranslation: 'תווית', category: 'Clothes', difficulty: 2, exampleEn: 'Price tag', exampleHe: 'תווית מחיר' },
    { englishWord: 'label', hebrewTranslation: 'תווית', category: 'Clothes', difficulty: 2, exampleEn: 'Clothing label', exampleHe: 'תווית בגד' },

    // Sports (20 words)
    { englishWord: 'ball', hebrewTranslation: 'כדור', category: 'Sports', difficulty: 1, exampleEn: 'Kick the ball', exampleHe: 'בעוט בכדור' },
    { englishWord: 'soccer', hebrewTranslation: 'כדורגל', category: 'Sports', difficulty: 1, exampleEn: 'I play soccer', exampleHe: 'אני משחק כדורגל' },
    { englishWord: 'basketball', hebrewTranslation: 'כדורסל', category: 'Sports', difficulty: 1, exampleEn: 'Basketball is fun', exampleHe: 'כדורסל זה כיף' },
    { englishWord: 'swim', hebrewTranslation: 'לשחות', category: 'Sports', difficulty: 1, exampleEn: 'I swim in the pool', exampleHe: 'אני שוחה בבריכה' },
    { englishWord: 'bike', hebrewTranslation: 'אופניים', category: 'Sports', difficulty: 1, exampleEn: 'Ride a bike', exampleHe: 'רכב על אופניים' },
    { englishWord: 'tennis', hebrewTranslation: 'טניס', category: 'Sports', difficulty: 1, exampleEn: 'I play tennis', exampleHe: 'אני משחק טניס' },
    { englishWord: 'running', hebrewTranslation: 'ריצה', category: 'Sports', difficulty: 1, exampleEn: 'I like running', exampleHe: 'אני אוהב לרוץ' },
    { englishWord: 'jump', hebrewTranslation: 'קפיצה', category: 'Sports', difficulty: 1, exampleEn: 'High jump', exampleHe: 'קפיצה גבוהה' },
    { englishWord: 'team', hebrewTranslation: 'קבוצה', category: 'Sports', difficulty: 1, exampleEn: 'My team wins', exampleHe: 'הקבוצה שלי מנצחת' },
    { englishWord: 'game', hebrewTranslation: 'משחק', category: 'Sports', difficulty: 1, exampleEn: 'Fun game', exampleHe: 'משחק כיף' },
    { englishWord: 'player', hebrewTranslation: 'שחקן', category: 'Sports', difficulty: 1, exampleEn: 'Good player', exampleHe: 'שחקן טוב' },
    { englishWord: 'coach', hebrewTranslation: 'מאמן', category: 'Sports', difficulty: 1, exampleEn: 'My coach is nice', exampleHe: 'המאמן שלי נחמד' },
    { englishWord: 'stadium', hebrewTranslation: 'אצטדיון', category: 'Sports', difficulty: 1, exampleEn: 'Big stadium', exampleHe: 'אצטדיון גדול' },
    { englishWord: 'goal', hebrewTranslation: 'שער', category: 'Sports', difficulty: 1, exampleEn: 'Score a goal', exampleHe: 'כבש שער' },
    { englishWord: 'winner', hebrewTranslation: 'מנצח', category: 'Sports', difficulty: 1, exampleEn: 'I am the winner', exampleHe: 'אני המנצח' },
    { englishWord: 'medal', hebrewTranslation: 'מדליה', category: 'Sports', difficulty: 1, exampleEn: 'Gold medal', exampleHe: 'מדליית זהב' },
    { englishWord: 'exercise', hebrewTranslation: 'אימון', category: 'Sports', difficulty: 1, exampleEn: 'Daily exercise', exampleHe: 'אימון יומי' },
    { englishWord: 'field', hebrewTranslation: 'מגרש', category: 'Sports', difficulty: 1, exampleEn: 'Sports field', exampleHe: 'מגרש ספורט' },
    { englishWord: 'race', hebrewTranslation: 'מירוץ', category: 'Sports', difficulty: 1, exampleEn: 'Running race', exampleHe: 'מירוץ ריצה' },
    { englishWord: 'swimming', hebrewTranslation: 'שחייה', category: 'Sports', difficulty: 1, exampleEn: 'Swimming is fun', exampleHe: 'שחייה זה כיף' },
    { englishWord: 'bat', hebrewTranslation: 'מחבט', category: 'Sports', difficulty: 2, exampleEn: 'Baseball bat', exampleHe: 'מחבט בייסבול' },
    { englishWord: 'net', hebrewTranslation: 'רשת', category: 'Sports', difficulty: 2, exampleEn: 'Tennis net', exampleHe: 'רשת טניס' },
    { englishWord: 'racket', hebrewTranslation: 'מחבט', category: 'Sports', difficulty: 2, exampleEn: 'Tennis racket', exampleHe: 'מחבט טניס' },
    { englishWord: 'helmet', hebrewTranslation: 'קסדה', category: 'Sports', difficulty: 2, exampleEn: 'Bike helmet', exampleHe: 'קסדת אופניים' },
    { englishWord: 'paddle', hebrewTranslation: 'משוט', category: 'Sports', difficulty: 2, exampleEn: 'Kayak paddle', exampleHe: 'משוט קיאק' },
    { englishWord: 'skis', hebrewTranslation: 'מגלשיים', category: 'Sports', difficulty: 2, exampleEn: 'Snow skis', exampleHe: 'מגלשיים שלג' },
    { englishWord: 'skates', hebrewTranslation: 'מחליקיים', category: 'Sports', difficulty: 2, exampleEn: 'Ice skates', exampleHe: 'מחליקיים קרח' },
    { englishWord: 'goggles', hebrewTranslation: 'משקפי מגן', category: 'Sports', difficulty: 2, exampleEn: 'Swimming goggles', exampleHe: 'משקפי שחייה' },
    { englishWord: 'whistle', hebrewTranslation: 'משרוקית', category: 'Sports', difficulty: 2, exampleEn: 'Referee whistle', exampleHe: 'משרוקית שופט' },
    { englishWord: 'trophy', hebrewTranslation: 'גביע', category: 'Sports', difficulty: 2, exampleEn: 'Win a trophy', exampleHe: 'זכה בגביע' },
    { englishWord: 'cup', hebrewTranslation: 'כוס', category: 'Sports', difficulty: 2, exampleEn: 'World cup', exampleHe: 'גביע עולם' },
    { englishWord: 'ribbon', hebrewTranslation: 'סרט', category: 'Sports', difficulty: 2, exampleEn: 'First place ribbon', exampleHe: 'סרט מקום ראשון' },
    { englishWord: 'badge', hebrewTranslation: 'תג', category: 'Sports', difficulty: 2, exampleEn: 'Team badge', exampleHe: 'תג קבוצה' },
    { englishWord: 'uniform', hebrewTranslation: 'מדים', category: 'Sports', difficulty: 2, exampleEn: 'Team uniform', exampleHe: 'מדים קבוצה' },
    { englishWord: 'jersey', hebrewTranslation: 'ג\'רסי', category: 'Sports', difficulty: 2, exampleEn: 'Team jersey', exampleHe: 'ג\'רסי קבוצה' },
    { englishWord: 'cleats', hebrewTranslation: 'נעלי כדורגל', category: 'Sports', difficulty: 2, exampleEn: 'Soccer cleats', exampleHe: 'נעלי כדורגל' },
    { englishWord: 'gloves', hebrewTranslation: 'כפפות', category: 'Sports', difficulty: 2, exampleEn: 'Baseball gloves', exampleHe: 'כפפות בייסבול' },
    { englishWord: 'pads', hebrewTranslation: 'מגנים', category: 'Sports', difficulty: 2, exampleEn: 'Knee pads', exampleHe: 'מגני ברכיים' },
    { englishWord: 'timer', hebrewTranslation: 'שעון עצר', category: 'Sports', difficulty: 2, exampleEn: 'Stop timer', exampleHe: 'עצור שעון עצר' },
    { englishWord: 'scoreboard', hebrewTranslation: 'לוח תוצאות', category: 'Sports', difficulty: 2, exampleEn: 'Check scoreboard', exampleHe: 'בדוק לוח תוצאות' },

    // More Home items
    
    // Home category Level 3 (difficulty 2) - 20 words
    { englishWord: 'furniture', hebrewTranslation: 'ריהוט', category: 'Home', difficulty: 2, exampleEn: 'Beautiful furniture', exampleHe: 'ריהוט יפה' },
    { englishWord: 'appliance', hebrewTranslation: 'מכשיר', category: 'Home', difficulty: 2, exampleEn: 'Kitchen appliance', exampleHe: 'מכשיר מטבח' },
    { englishWord: 'cabinet', hebrewTranslation: 'ארון', category: 'Home', difficulty: 2, exampleEn: 'Kitchen cabinet', exampleHe: 'ארון מטבח' },
    { englishWord: 'drawer', hebrewTranslation: 'מגירה', category: 'Home', difficulty: 2, exampleEn: 'Open the drawer', exampleHe: 'פתח את המגירה' },
    { englishWord: 'shelf', hebrewTranslation: 'מדף', category: 'Home', difficulty: 2, exampleEn: 'Book shelf', exampleHe: 'מדף ספרים' },
    { englishWord: 'curtain', hebrewTranslation: 'וילון', category: 'Home', difficulty: 2, exampleEn: 'Close the curtain', exampleHe: 'סגור את הוילון' },
    { englishWord: 'carpet', hebrewTranslation: 'שטיח', category: 'Home', difficulty: 2, exampleEn: 'Soft carpet', exampleHe: 'שטיח רך' },
    { englishWord: 'cushion', hebrewTranslation: 'כרית', category: 'Home', difficulty: 2, exampleEn: 'Comfortable cushion', exampleHe: 'כרית נוחה' },
    { englishWord: 'vase', hebrewTranslation: 'אגרטל', category: 'Home', difficulty: 2, exampleEn: 'Flower vase', exampleHe: 'אגרטל פרחים' },
    { englishWord: 'candle', hebrewTranslation: 'נר', category: 'Home', difficulty: 2, exampleEn: 'Light a candle', exampleHe: 'הדלק נר' },
    { englishWord: 'frame', hebrewTranslation: 'מסגרת', category: 'Home', difficulty: 2, exampleEn: 'Picture frame', exampleHe: 'מסגרת תמונה' },
    { englishWord: 'decoration', hebrewTranslation: 'קישוט', category: 'Home', difficulty: 2, exampleEn: 'Holiday decoration', exampleHe: 'קישוט חג' },
    { englishWord: 'basement', hebrewTranslation: 'מרתף', category: 'Home', difficulty: 2, exampleEn: 'Dark basement', exampleHe: 'מרתף חשוך' },
    { englishWord: 'attic', hebrewTranslation: 'עליית גג', category: 'Home', difficulty: 2, exampleEn: 'Old attic', exampleHe: 'עליית גג ישנה' },
    { englishWord: 'balcony', hebrewTranslation: 'מרפסת', category: 'Home', difficulty: 2, exampleEn: 'Beautiful balcony', exampleHe: 'מרפסת יפה' },
    { englishWord: 'porch', hebrewTranslation: 'מרפסת כניסה', category: 'Home', difficulty: 2, exampleEn: 'Front porch', exampleHe: 'מרפסת כניסה' },
    { englishWord: 'garage', hebrewTranslation: 'מוסך', category: 'Home', difficulty: 2, exampleEn: 'Car garage', exampleHe: 'מוסך מכוניות' },
    { englishWord: 'shed', hebrewTranslation: 'סככה', category: 'Home', difficulty: 2, exampleEn: 'Garden shed', exampleHe: 'סככת גן' },
    { englishWord: 'fence', hebrewTranslation: 'גדר', category: 'Home', difficulty: 2, exampleEn: 'Wooden fence', exampleHe: 'גדר עץ' },
    { englishWord: 'gate', hebrewTranslation: 'שער', category: 'Home', difficulty: 2, exampleEn: 'Open the gate', exampleHe: 'פתח את השער' },

    // Transportation (20 words)
    { englishWord: 'car', hebrewTranslation: 'מכונית', category: 'Transportation', difficulty: 1, exampleEn: 'I drive a car', exampleHe: 'אני נוהג במכונית' },
    { englishWord: 'bus', hebrewTranslation: 'אוטובוס', category: 'Transportation', difficulty: 1, exampleEn: 'I ride the bus', exampleHe: 'אני נוסע באוטובוס' },
    { englishWord: 'train', hebrewTranslation: 'רכבת', category: 'Transportation', difficulty: 1, exampleEn: 'The train is fast', exampleHe: 'הרכבת מהירה' },
    { englishWord: 'plane', hebrewTranslation: 'מטוס', category: 'Transportation', difficulty: 1, exampleEn: 'The plane flies', exampleHe: 'המטוס עף' },
    { englishWord: 'bike', hebrewTranslation: 'אופניים', category: 'Transportation', difficulty: 1, exampleEn: 'Ride a bike', exampleHe: 'רכב על אופניים' },
    { englishWord: 'boat', hebrewTranslation: 'סירה', category: 'Transportation', difficulty: 1, exampleEn: 'The boat sails', exampleHe: 'הסירה שטה' },
    { englishWord: 'ship', hebrewTranslation: 'ספינה', category: 'Transportation', difficulty: 1, exampleEn: 'Big ship', exampleHe: 'ספינה גדולה' },
    { englishWord: 'truck', hebrewTranslation: 'משאית', category: 'Transportation', difficulty: 1, exampleEn: 'The truck is big', exampleHe: 'המשאית גדולה' },
    { englishWord: 'motorcycle', hebrewTranslation: 'אופנוע', category: 'Transportation', difficulty: 1, exampleEn: 'Fast motorcycle', exampleHe: 'אופנוע מהיר' },
    { englishWord: 'taxi', hebrewTranslation: 'מונית', category: 'Transportation', difficulty: 1, exampleEn: 'Take a taxi', exampleHe: 'קח מונית' },
    { englishWord: 'subway', hebrewTranslation: 'רכבת תחתית', category: 'Transportation', difficulty: 1, exampleEn: 'The subway is underground', exampleHe: 'הרכבת התחתית מתחת לאדמה' },
    { englishWord: 'helicopter', hebrewTranslation: 'מסוק', category: 'Transportation', difficulty: 1, exampleEn: 'The helicopter flies', exampleHe: 'המסוק עף' },
    { englishWord: 'scooter', hebrewTranslation: 'קורקינט', category: 'Transportation', difficulty: 1, exampleEn: 'Ride a scooter', exampleHe: 'רכב על קורקינט' },
    { englishWord: 'wheel', hebrewTranslation: 'גלגל', category: 'Transportation', difficulty: 1, exampleEn: 'Four wheels', exampleHe: 'ארבעה גלגלים' },
    { englishWord: 'road', hebrewTranslation: 'כביש', category: 'Transportation', difficulty: 1, exampleEn: 'The road is long', exampleHe: 'הכביש ארוך' },
    { englishWord: 'street', hebrewTranslation: 'רחוב', category: 'Transportation', difficulty: 1, exampleEn: 'My street is quiet', exampleHe: 'הרחוב שלי שקט' },
    { englishWord: 'bridge', hebrewTranslation: 'גשר', category: 'Transportation', difficulty: 1, exampleEn: 'Cross the bridge', exampleHe: 'חצה את הגשר' },
    { englishWord: 'wheel', hebrewTranslation: 'גלגל', category: 'Transportation', difficulty: 2, exampleEn: 'Car wheel', exampleHe: 'גלגל מכונית' },
    { englishWord: 'door', hebrewTranslation: 'דלת', category: 'Transportation', difficulty: 2, exampleEn: 'Car door', exampleHe: 'דלת מכונית' },
    { englishWord: 'window', hebrewTranslation: 'חלון', category: 'Transportation', difficulty: 2, exampleEn: 'Car window', exampleHe: 'חלון מכונית' },
    { englishWord: 'seat', hebrewTranslation: 'מושב', category: 'Transportation', difficulty: 2, exampleEn: 'Car seat', exampleHe: 'מושב מכונית' },
    { englishWord: 'belt', hebrewTranslation: 'חגורה', category: 'Transportation', difficulty: 2, exampleEn: 'Seat belt', exampleHe: 'חגורת בטיחות' },
    { englishWord: 'horn', hebrewTranslation: 'צופר', category: 'Transportation', difficulty: 2, exampleEn: 'Car horn', exampleHe: 'צופר מכונית' },
    { englishWord: 'light', hebrewTranslation: 'אור', category: 'Transportation', difficulty: 2, exampleEn: 'Car light', exampleHe: 'אור מכונית' },
    { englishWord: 'mirror', hebrewTranslation: 'מראה', category: 'Transportation', difficulty: 2, exampleEn: 'Side mirror', exampleHe: 'מראה צד' },
    { englishWord: 'engine', hebrewTranslation: 'מנוע', category: 'Transportation', difficulty: 2, exampleEn: 'Car engine', exampleHe: 'מנוע מכונית' },
    { englishWord: 'brake', hebrewTranslation: 'בלם', category: 'Transportation', difficulty: 2, exampleEn: 'Press brake', exampleHe: 'לחץ על הבלם' },
    { englishWord: 'gas', hebrewTranslation: 'דלק', category: 'Transportation', difficulty: 2, exampleEn: 'Fill gas', exampleHe: 'מלא דלק' },
    { englishWord: 'key', hebrewTranslation: 'מפתח', category: 'Transportation', difficulty: 2, exampleEn: 'Car key', exampleHe: 'מפתח מכונית' },
    { englishWord: 'lock', hebrewTranslation: 'מנעול', category: 'Transportation', difficulty: 2, exampleEn: 'Car lock', exampleHe: 'מנעול מכונית' },
    { englishWord: 'trunk', hebrewTranslation: 'תא מטען', category: 'Transportation', difficulty: 2, exampleEn: 'Car trunk', exampleHe: 'תא מטען מכונית' },
    { englishWord: 'hood', hebrewTranslation: 'מכסה מנוע', category: 'Transportation', difficulty: 2, exampleEn: 'Car hood', exampleHe: 'מכסה מנוע מכונית' },
    { englishWord: 'bumper', hebrewTranslation: 'פגוש', category: 'Transportation', difficulty: 2, exampleEn: 'Car bumper', exampleHe: 'פגוש מכונית' },
    { englishWord: 'tire', hebrewTranslation: 'צמיג', category: 'Transportation', difficulty: 2, exampleEn: 'Flat tire', exampleHe: 'צמיג שטוח' },
    { englishWord: 'handle', hebrewTranslation: 'ידית', category: 'Transportation', difficulty: 2, exampleEn: 'Door handle', exampleHe: 'ידית דלת' },
    { englishWord: 'steering', hebrewTranslation: 'הגה', category: 'Transportation', difficulty: 2, exampleEn: 'Steering wheel', exampleHe: 'גלגל הגה' },
    { englishWord: 'pedal', hebrewTranslation: 'דוושה', category: 'Transportation', difficulty: 2, exampleEn: 'Gas pedal', exampleHe: 'דוושת דלק' },
    { englishWord: 'parking', hebrewTranslation: 'חניה', category: 'Transportation', difficulty: 1, exampleEn: 'Parking lot', exampleHe: 'מגרש חניה' },
    { englishWord: 'driver', hebrewTranslation: 'נהג', category: 'Transportation', difficulty: 1, exampleEn: 'Good driver', exampleHe: 'נהג טוב' },
    { englishWord: 'van', hebrewTranslation: 'טנדר', category: 'Transportation', difficulty: 1, exampleEn: 'Big van', exampleHe: 'טנדר גדול' },

    // Weather (20 words)
    { englishWord: 'sunny', hebrewTranslation: 'שמשי', category: 'Weather', difficulty: 1, exampleEn: 'It is sunny today', exampleHe: 'היום שמשי' },
    { englishWord: 'rainy', hebrewTranslation: 'גשום', category: 'Weather', difficulty: 1, exampleEn: 'Rainy day', exampleHe: 'יום גשום' },
    { englishWord: 'cloudy', hebrewTranslation: 'מעונן', category: 'Weather', difficulty: 1, exampleEn: 'Cloudy sky', exampleHe: 'שמיים מעוננים' },
    { englishWord: 'windy', hebrewTranslation: 'רוח', category: 'Weather', difficulty: 1, exampleEn: 'It is windy', exampleHe: 'יש רוח' },
    { englishWord: 'snowy', hebrewTranslation: 'מושלג', category: 'Weather', difficulty: 1, exampleEn: 'Snowy winter', exampleHe: 'חורף מושלג' },
    { englishWord: 'hot', hebrewTranslation: 'חם', category: 'Weather', difficulty: 1, exampleEn: 'It is hot today', exampleHe: 'היום חם' },
    { englishWord: 'cold', hebrewTranslation: 'קר', category: 'Weather', difficulty: 1, exampleEn: 'It is cold outside', exampleHe: 'קר בחוץ' },
    { englishWord: 'warm', hebrewTranslation: 'חמים', category: 'Weather', difficulty: 1, exampleEn: 'Warm weather', exampleHe: 'מזג אוויר חמים' },
    { englishWord: 'cool', hebrewTranslation: 'מעולה', category: 'Weather', difficulty: 1, exampleEn: 'Cool breeze', exampleHe: 'רוח נעימה' },
    { englishWord: 'storm', hebrewTranslation: 'סערה', category: 'Weather', difficulty: 1, exampleEn: 'Big storm', exampleHe: 'סערה גדולה' },
    { englishWord: 'thunder', hebrewTranslation: 'רעם', category: 'Weather', difficulty: 1, exampleEn: 'Loud thunder', exampleHe: 'רעם חזק' },
    { englishWord: 'lightning', hebrewTranslation: 'ברק', category: 'Weather', difficulty: 1, exampleEn: 'Bright lightning', exampleHe: 'ברק בהיר' },
    { englishWord: 'fog', hebrewTranslation: 'ערפל', category: 'Weather', difficulty: 1, exampleEn: 'Thick fog', exampleHe: 'ערפל כבד' },
    { englishWord: 'rainbow', hebrewTranslation: 'קשת', category: 'Weather', difficulty: 1, exampleEn: 'Beautiful rainbow', exampleHe: 'קשת יפה' },
    { englishWord: 'spring', hebrewTranslation: 'אביב', category: 'Weather', difficulty: 2, exampleEn: 'Spring season', exampleHe: 'עונת אביב' },
    { englishWord: 'summer', hebrewTranslation: 'קיץ', category: 'Weather', difficulty: 2, exampleEn: 'Hot summer', exampleHe: 'קיץ חם' },
    { englishWord: 'fall', hebrewTranslation: 'סתיו', category: 'Weather', difficulty: 2, exampleEn: 'Beautiful fall', exampleHe: 'סתיו יפה' },
    { englishWord: 'winter', hebrewTranslation: 'חורף', category: 'Weather', difficulty: 2, exampleEn: 'Cold winter', exampleHe: 'חורף קר' },
    { englishWord: 'cloud', hebrewTranslation: 'ענן', category: 'Weather', difficulty: 2, exampleEn: 'White cloud', exampleHe: 'ענן לבן' },
    { englishWord: 'wind', hebrewTranslation: 'רוח', category: 'Weather', difficulty: 2, exampleEn: 'Strong wind', exampleHe: 'רוח חזקה' },
    { englishWord: 'rain', hebrewTranslation: 'גשם', category: 'Weather', difficulty: 2, exampleEn: 'Heavy rain', exampleHe: 'גשם חזק' },
    { englishWord: 'snow', hebrewTranslation: 'שלג', category: 'Weather', difficulty: 2, exampleEn: 'White snow', exampleHe: 'שלג לבן' },
    { englishWord: 'ice', hebrewTranslation: 'קרח', category: 'Weather', difficulty: 2, exampleEn: 'Slippery ice', exampleHe: 'קרח חלק' },
    { englishWord: 'sun', hebrewTranslation: 'שמש', category: 'Weather', difficulty: 2, exampleEn: 'Bright sun', exampleHe: 'שמש בהירה' },
    { englishWord: 'moon', hebrewTranslation: 'ירח', category: 'Weather', difficulty: 2, exampleEn: 'Full moon', exampleHe: 'ירח מלא' },
    { englishWord: 'star', hebrewTranslation: 'כוכב', category: 'Weather', difficulty: 2, exampleEn: 'Bright star', exampleHe: 'כוכב בהיר' },
    { englishWord: 'sky', hebrewTranslation: 'שמיים', category: 'Weather', difficulty: 2, exampleEn: 'Blue sky', exampleHe: 'שמיים כחולים' },
    { englishWord: 'ground', hebrewTranslation: 'אדמה', category: 'Weather', difficulty: 2, exampleEn: 'Wet ground', exampleHe: 'אדמה רטובה' },
    { englishWord: 'puddle', hebrewTranslation: 'שלולית', category: 'Weather', difficulty: 2, exampleEn: 'Water puddle', exampleHe: 'שלולית מים' },
    { englishWord: 'drop', hebrewTranslation: 'טיפה', category: 'Weather', difficulty: 2, exampleEn: 'Rain drop', exampleHe: 'טיפת גשם' },
    { englishWord: 'flake', hebrewTranslation: 'פתית', category: 'Weather', difficulty: 2, exampleEn: 'Snow flake', exampleHe: 'פתית שלג' },
    { englishWord: 'breeze', hebrewTranslation: 'בריזה', category: 'Weather', difficulty: 2, exampleEn: 'Cool breeze', exampleHe: 'בריזה נעימה' },
    { englishWord: 'gust', hebrewTranslation: 'משב רוח', category: 'Weather', difficulty: 2, exampleEn: 'Strong gust', exampleHe: 'משב רוח חזק' },
    { englishWord: 'shade', hebrewTranslation: 'צל', category: 'Weather', difficulty: 2, exampleEn: 'Cool shade', exampleHe: 'צל קריר' },
    { englishWord: 'season', hebrewTranslation: 'עונה', category: 'Weather', difficulty: 1, exampleEn: 'Spring season', exampleHe: 'עונת אביב' },
    { englishWord: 'spring', hebrewTranslation: 'אביב', category: 'Weather', difficulty: 1, exampleEn: 'Beautiful spring', exampleHe: 'אביב יפה' },
    { englishWord: 'summer', hebrewTranslation: 'קיץ', category: 'Weather', difficulty: 1, exampleEn: 'Hot summer', exampleHe: 'קיץ חם' },
    { englishWord: 'autumn', hebrewTranslation: 'סתיו', category: 'Weather', difficulty: 1, exampleEn: 'Colorful autumn', exampleHe: 'סתיו צבעוני' },
    { englishWord: 'winter', hebrewTranslation: 'חורף', category: 'Weather', difficulty: 1, exampleEn: 'Cold winter', exampleHe: 'חורף קר' },
    { englishWord: 'weather', hebrewTranslation: 'מזג אוויר', category: 'Weather', difficulty: 1, exampleEn: 'Nice weather', exampleHe: 'מזג אוויר נעים' },
  ];

  for (const wordData of words) {
    await prisma.word.upsert({
      where: {
        id: `word-${wordData.englishWord}`,
      },
      update: {
        ...wordData,
      },
      create: {
        id: `word-${wordData.englishWord}`,
        ...wordData,
      },
    });
  }

  console.log(`✅ Created ${words.length} words`);

  // Create level state for child
  await prisma.levelState.upsert({
    where: { childId: child.id },
    update: {},
    create: {
      childId: child.id,
      level: 1,
      xp: 0,
    },
  });

  console.log('✅ Level state created');

  console.log('🎉 Seed completed!');
  console.log('📌 Default PIN: 1234');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
